platform:

  server: http://localhost:4723/wd/hub

  android:
    platformName: android
    platformVersion: 10
    deviceName: MotoOneAction
    udid: motooneaction
    app: /App/app.apk
    automationName: UiAutomator2
    appActivity: com.example.MainActivity
    autoGrantPermissions: True
    autoAcceptAlerts: True
    noReset: True
    disableWindowAnimation: False
    newCommandTimeout: 20000
    waitForIdleTimeout: 2000
  
  ios:
    platformName: iOS
    automationName: xcuitest
    bundleId: com.example.app
    deviceName: iPhone Simulator
    platformVersion: 11.4
    app: /App/app.ipa
    udid: iphonesimulator
    noReset: True
    waitForQuiescence: False
    wdaEventloopIdleDelay: 3
    eventLoopIdleDelaySec: 1
    useJSONSource: True
    useNewWDA: True
    fullReset: False
    autoGrantPermissions: True
    autoAcceptAlerts: True
    disableWindowAnimation: False
    autoDismissAlerts: True
